BEGIN;
TRUNCATE "auth_user_user_permissions", "afijo_movimiento", "afijo_activodepreciacion", "auth_permission", "auth_user_groups", "afijo_planta", "afijo_activo", "django_admin_log", "auth_user", "django_session", "afijo_tipodepreciacion", "afijo_estado", "django_content_type", "auth_group_permissions", "auth_group";
SELECT setval(pg_get_serial_sequence('"afijo_estado"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"afijo_tipodepreciacion"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"afijo_planta"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"afijo_activo"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"afijo_movimiento"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"afijo_activodepreciacion"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_user_groups"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_user_user_permissions"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), 1, false);
COMMIT;
