# Generated by Django 2.2.12 on 2021-01-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=180, verbose_name='Ubicación')),
                ('fecha_apertura', models.DateField(verbose_name='Fecha Apertura Planta')),
                ('duracion_concesion', models.IntegerField(default=8, verbose_name='Duración de la Concesión')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha Inicio Depreciación')),
                ('fecha_termino', models.DateField(null=True, verbose_name='Fecha Término Depreciación')),
                ('duracion_maxima', models.IntegerField(default=5, verbose_name='Duración Depreciación [años]')),
                ('valor', models.BigIntegerField(verbose_name='Valor')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('tipoActivo', models.CharField(choices=[('M', 'Mueble'), ('I', 'Inmueble')], default='M', max_length=1)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Estado')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afijo.Planta')),
            ],
        ),
    ]
