# Generated by Django 2.2.2 on 2024-02-15 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoDepAcum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_id', models.BigIntegerField(verbose_name='Id. Activo')),
                ('activo_tipo', models.CharField(max_length=250, verbose_name='Tipo de Activo')),
                ('activo_nombre', models.CharField(max_length=250, verbose_name='Nombre Activo')),
                ('numero_factura', models.CharField(max_length=250, verbose_name='Número Factura')),
                ('proveedor', models.CharField(max_length=250, verbose_name='Proveedor')),
                ('activo_fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('activo_valor', models.BigIntegerField(verbose_name='Valor Compra')),
                ('planta_nombre', models.CharField(max_length=250, verbose_name='Nombre Planta')),
                ('planta_ubicacion', models.CharField(max_length=250, verbose_name='Ubicación Planta')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Concesión')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Término Dep.')),
                ('fecha_depreciacion', models.DateField(verbose_name='Fecha Inicio Dep.')),
                ('valor_depreciacion', models.BigIntegerField(verbose_name='Depreciación Mensual')),
                ('acum_total', models.BigIntegerField(verbose_name='Acumuluado Total')),
                ('acum_anual', models.BigIntegerField(verbose_name='Acumuluado Ejercicio')),
                ('duracion_real', models.IntegerField(verbose_name='Duración Real en [meses]')),
                ('dep_acum', models.BigIntegerField(verbose_name='Depreciación Acumulada')),
                ('neto', models.BigIntegerField(verbose_name='Neto')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('planta_id', models.BigIntegerField(verbose_name='Id. Planta')),
            ],
            options={
                'db_table': 'afijo_v_deprec_acum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivoDepMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_id', models.BigIntegerField(verbose_name='Id. Activo')),
                ('activo_tipo', models.CharField(max_length=250, verbose_name='Tipo de Activo')),
                ('activo_nombre', models.CharField(max_length=250, verbose_name='Nombre Activo')),
                ('numero_factura', models.CharField(max_length=250, verbose_name='Número Factura')),
                ('proveedor', models.CharField(max_length=250, verbose_name='Proveedor')),
                ('activo_fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('activo_valor', models.BigIntegerField(verbose_name='Valor Compra')),
                ('planta_nombre', models.CharField(max_length=250, verbose_name='Nombre Planta')),
                ('planta_ubicacion', models.CharField(max_length=250, verbose_name='Ubicación Planta')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Concesión')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Término Dep.')),
                ('fecha_depreciacion', models.DateField(verbose_name='Fecha Inicio Dep.')),
                ('valor_depreciacion', models.BigIntegerField(verbose_name='Depreciación Mensual')),
                ('acum_total', models.BigIntegerField(verbose_name='Acumuluado Total')),
                ('acum_anual', models.BigIntegerField(verbose_name='Acumuluado Ejercicio')),
                ('duracion_real', models.IntegerField(verbose_name='Duración Real en [meses]')),
                ('dep_acum', models.BigIntegerField(verbose_name='Depreciación Acumulada')),
                ('neto', models.BigIntegerField(verbose_name='Neto')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('planta_id', models.BigIntegerField(verbose_name='Id. Planta')),
            ],
            options={
                'db_table': 'afijo_v_deprec_max',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivoDepMin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_id', models.BigIntegerField(verbose_name='Id. Activo')),
                ('activo_tipo', models.CharField(max_length=250, verbose_name='Tipo de Activo')),
                ('activo_nombre', models.CharField(max_length=250, verbose_name='Nombre Activo')),
                ('numero_factura', models.CharField(max_length=250, verbose_name='Número Factura')),
                ('proveedor', models.CharField(max_length=250, verbose_name='Proveedor')),
                ('activo_fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('activo_valor', models.BigIntegerField(verbose_name='Valor Compra')),
                ('planta_nombre', models.CharField(max_length=250, verbose_name='Nombre Planta')),
                ('planta_ubicacion', models.CharField(max_length=250, verbose_name='Ubicación Planta')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Concesión')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Término Dep.')),
                ('fecha_depreciacion', models.DateField(verbose_name='Fecha Inicio Dep.')),
                ('valor_depreciacion', models.BigIntegerField(verbose_name='Depreciación Mensual')),
                ('acum_total', models.BigIntegerField(verbose_name='Acumuluado Total')),
                ('acum_anual', models.BigIntegerField(verbose_name='Acumuluado Ejercicio')),
                ('duracion_real', models.IntegerField(verbose_name='Duración Real en [meses]')),
                ('dep_acum', models.BigIntegerField(verbose_name='Depreciación Acumulada')),
                ('neto', models.BigIntegerField(verbose_name='Neto')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('planta_id', models.BigIntegerField(verbose_name='Id. Planta')),
            ],
            options={
                'db_table': 'afijo_v_deprec_min',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('modelo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo')),
                ('contab', models.CharField(max_length=20, verbose_name='Cta Contable')),
                ('linea', models.CharField(default=1, max_length=2, verbose_name='Línea')),
                ('numero_interno', models.CharField(default=1, max_length=5, verbose_name='Número Interno')),
                ('codigo_interno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código Interno')),
                ('serie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Serie')),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ubicación')),
                ('factura_fisica', models.CharField(blank=True, max_length=60, null=True, verbose_name='Factura Física')),
                ('proveedor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Factura Física')),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Factura Física')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Depreciación')),
                ('duracion_maxima', models.IntegerField(default=36, verbose_name='Duración Depreciación [meses]')),
                ('duracion_clase', models.CharField(choices=[('C', 'Desde Concesión'), ('C24', 'Dos años mas desde Concesión'), ('T', 'Tributaria')], default='T', max_length=5)),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha Término Depreciación')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('vida_util_compra', models.BooleanField(default=False, verbose_name='Vida útil desde la compra')),
                ('valor', models.BigIntegerField(verbose_name='Valor')),
                ('valorResidual', models.BigIntegerField(default=0, verbose_name='Valor Residual')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('tipoActivo', models.CharField(choices=[('A', 'Acondicionamiento'), ('E', 'Edificio'), ('O', 'Obras en curso'), ('M', 'Maquinaria'), ('C', 'Equipos de computación'), ('S', 'Software'), ('U', 'Muebles y Utiles'), ('V', 'Vehiculos')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='TipoDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'tipo de depreciación',
                'verbose_name_plural': 'tipos de depreciación',
            },
        ),
        migrations.CreateModel(
            name='TipoFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo y Familia',
                'verbose_name_plural': 'Tipos y Familias',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=180, verbose_name='Ubicación')),
                ('fecha_apertura', models.DateField(verbose_name='Fecha Apertura')),
                ('fecha_depreciacion', models.DateField(verbose_name='Fecha Inicio Depreciación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Concesión')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Término Concesión')),
                ('duracion_concesion', models.IntegerField(verbose_name='Vida Útil Proyecto')),
                ('activa', models.BooleanField(default=True, verbose_name='Depreciación Activa')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afijo.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_movim', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Registro')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha Cambio')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Activo')),
                ('planta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaDestino', to='afijo.Planta')),
                ('planta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaOrigen', to='afijo.Planta')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Estado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afijo.TipoFamilia'),
        ),
        migrations.AddField(
            model_name='activo',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afijo.Planta'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipoDepreciacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afijo.TipoDepreciacion'),
        ),
        migrations.CreateModel(
            name='ActivoDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('valor_depreciacion', models.BigIntegerField(verbose_name='Valor Depreciación')),
                ('valor_contable', models.BigIntegerField(default=0, verbose_name='Valor Contable')),
                ('duracion_real', models.IntegerField(default=0, verbose_name='Duración Real')),
                ('acum_total', models.BigIntegerField(verbose_name='Acumulado Total')),
                ('acum_anual', models.BigIntegerField(verbose_name='Acumulado Anual')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Activo')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Planta')),
            ],
            options={
                'unique_together': {('activo', 'planta', 'periodo')},
            },
        ),
    ]
