# Generated by Django 2.2.2 on 2021-01-17 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='fecha_depreciacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio Depreciación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Término Concesión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Término Concesión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Depreciación'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Término Depreciación'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='fecha_apertura',
            field=models.DateField(verbose_name='Fecha Inicio Operación'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='PlantaDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor', models.BigIntegerField(verbose_name='Valor')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Planta')),
            ],
        ),
    ]
