# Generated by Django 3.2.7 on 2021-10-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='sobre_termino',
            field=models.IntegerField(default=0, verbose_name='Sobre tiempo depreciación'),
        ),
    ]
