# Generated by Django 2.2.2 on 2024-02-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0002_planta_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='direccion',
        ),
    ]
