# Generated by Django 2.2.2 on 2021-01-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0002_auto_20210117_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantaDepreciacion',
            new_name='depreciacion',
        ),
    ]
