# Generated by Django 2.2.2 on 2021-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0003_auto_20210117_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
        ),
    ]
