# Generated by Django 3.2.7 on 2021-10-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0003_remove_planta_sobre_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='extra_duracion',
        ),
        migrations.AddField(
            model_name='activo',
            name='duracion_clase',
            field=models.CharField(choices=[('C', 'Desde Concesión'), ('C24', 'Dos años mas desde Concesión'), ('T', 'Tributaria')], default='T', max_length=5),
        ),
    ]
