# Generated by Django 3.2.7 on 2021-10-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0004_auto_20211009_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='vida_util_compra',
            field=models.BooleanField(default=False, verbose_name='Vida útil desde la compra'),
        ),
    ]
