# Generated by Django 2.2.2 on 2024-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0004_planta_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='alias',
            field=models.CharField(max_length=20, unique=True, verbose_name='Alias'),
        ),
    ]
