# Generated by Django 2.2.2 on 2021-05-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0005_activo_tipodepreciacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciacion',
            options={'verbose_name': 'depreciación', 'verbose_name_plural': 'depreciación anual'},
        ),
        migrations.AlterModelOptions(
            name='tipodepreciacion',
            options={'verbose_name': 'tipo de depreciación', 'verbose_name_plural': 'tipos de depreciación'},
        ),
        migrations.AddField(
            model_name='activo',
            name='valorResidual',
            field=models.BigIntegerField(default=0, verbose_name='Valor Residual'),
        ),
    ]
