# Generated by Django 5.0 on 2024-02-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afijo", "0005_auto_20240215_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activodepreciacion",
            name="valor_depreciacion",
            field=models.DecimalField(
                decimal_places=5, max_digits=18, verbose_name="Valor Depreciación"
            ),
        ),
    ]
