# Generated by Django 3.2.7 on 2021-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0005_activo_vida_util_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='activodepreciacion',
            name='duracion_real',
            field=models.IntegerField(default=0, verbose_name='Duración Real'),
        ),
    ]
