# Generated by Django 2.2.2 on 2021-05-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0006_auto_20210501_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Año')),
                ('valorDepreciacion', models.BigIntegerField(verbose_name='Valor Depreciación')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Activo')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Planta')),
            ],
            options={
                'unique_together': {('activo', 'planta', 'year')},
            },
        ),
    ]
