# Generated by Django 2.2.2 on 2021-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0007_activodepreciacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activodepreciacion',
            old_name='valorDepreciacion',
            new_name='valor_depreciacion',
        ),
        migrations.AddField(
            model_name='activodepreciacion',
            name='valor_contable',
            field=models.BigIntegerField(default=0, verbose_name='Valor Contable'),
        ),
    ]
