# Generated by Django 2.2.2 on 2021-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0008_auto_20210504_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='fecha_apertura',
            field=models.DateField(verbose_name='Fecha Apertura'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio Concesión'),
        ),
    ]
