# Generated by Django 2.2.2 on 2021-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0009_auto_20210505_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='duracion_concesion',
            field=models.IntegerField(verbose_name='Duración de la Concesión'),
        ),
    ]
