# Generated by Django 2.2.2 on 2021-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0010_auto_20210505_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipoActivo',
            field=models.CharField(choices=[('1', 'Mueble'), ('I', 'Inmueble'), ('E', 'Edificio'), ('M', 'Maquinaria'), ('C', 'Equipos de computación'), ('S', 'Software')], default='M', max_length=1),
        ),
    ]
