# Generated by Django 2.2.2 on 2021-05-12 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0012_auto_20210506_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='activodepreciacion',
            name='periodo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activodepreciacion',
            unique_together={('activo', 'planta', 'periodo')},
        ),
        migrations.RemoveField(
            model_name='activodepreciacion',
            name='year',
        ),
    ]
