# Generated by Django 2.2.2 on 2021-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0013_auto_20210511_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
    ]
