# Generated by Django 2.2.2 on 2021-05-12 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0014_activo_fecha_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_movim', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='TS Registro')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha Cambio')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afijo.Activo')),
                ('planta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaDestino', to='afijo.Planta')),
                ('planta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaOrigen', to='afijo.Planta')),
            ],
        ),
    ]
