# Generated by Django 2.2.2 on 2021-05-14 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0015_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ts_movim',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Registro'),
        ),
    ]
