# Generated by Django 2.2.2 on 2021-05-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0016_auto_20210514_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
    ]
