# Generated by Django 2.2.2 on 2021-08-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0018_auto_20210830_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
    ]
