# Generated by Django 2.2.2 on 2021-08-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0019_auto_20210830_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('codigo',), 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
    ]
