# Generated by Django 2.2.2 on 2021-08-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0020_auto_20210830_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo y Familia',
                'verbose_name_plural': 'Tipos y Familias',
                'ordering': ('nombre',),
            },
        ),
    ]
