# Generated by Django 2.2.2 on 2021-08-31 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0021_tipofamilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='codigo_interno',
            field=models.CharField(default='', max_length=30, verbose_name='Código Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afijo.TipoFamilia'),
        ),
        migrations.AddField(
            model_name='activo',
            name='modelo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='serie',
            field=models.CharField(default=0, max_length=30, verbose_name='Serie'),
            preserve_default=False,
        ),
    ]
