# Generated by Django 2.2.2 on 2021-08-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0022_auto_20210830_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código Interno'),
        ),
    ]
