# Generated by Django 2.2.2 on 2021-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0024_activo_numero_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='linea',
            field=models.CharField(default=1, max_length=2, verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(max_length=30, verbose_name='Número de Serie'),
        ),
    ]
