# Generated by Django 2.2.2 on 2021-09-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0025_auto_20210902_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='factura_fisica',
            field=models.CharField(default=1, max_length=60, verbose_name='Factura Física'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipoActivo',
            field=models.CharField(choices=[('A', 'Acondicionamiento'), ('E', 'Edificio'), ('O', 'Obras en curso'), ('M', 'Maquinaria'), ('C', 'Equipos de computación'), ('S', 'Software'), ('U', 'Muebles y Utiles')], default='M', max_length=1),
        ),
    ]
