# Generated by Django 2.2.2 on 2021-09-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0026_auto_20210914_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Factura Física'),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura Física'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='factura_fisica',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Factura Física'),
        ),
    ]
