# Generated by Django 2.2.2 on 2021-09-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0027_auto_20210914_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
