# Generated by Django 2.2.2 on 2021-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0028_auto_20210915_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Depreciación Activa'),
        ),
    ]
