# Generated by Django 2.2.2 on 2021-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afijo', '0029_planta_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='numero_interno',
            field=models.CharField(default=1, max_length=5, verbose_name='Número Interno'),
        ),
    ]
